.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. nullion_qt test_nullion_qt
clean: FORCE
	$(MAKE) -C .. nullion_qt_clean test_nullion_qt_clean
check: FORCE
	$(MAKE) -C .. test_nullion_qt_check
nullion-qt nullion-qt.exe: FORCE
	 $(MAKE) -C .. nullion_qt
apk: FORCE
	$(MAKE) -C .. nullion_qt_apk
